name: i_store
version: 1.0.0+1
description: Ecome App Store
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_launcher_name: 
  name: iStore

flutter_icons: 
  android: app_icon_round
  image_path: assets/images/app_icon_round.png
  ios: true

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

