name: i_store
description: Ecome App Store
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # Package
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  animated_splash_screen: ^1.1.0
  #get: ^4.1.4
  #intl: ^0.17.0
  #provider: ^5.0.0
  #google_fonts: ^2.0.0


dev_dependencies:
  #change_app_package_name: ^1.0.0
  #flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "app_icon_round"
  ios: true
  image_path: "images/app_icon_round.png"

flutter:
  uses-material-design: true
  assets:
    - images/
