name: i_store
version: 1.0.0+1
description: Ecome App Store
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.3.8
  animated_splash_screen: ^1.1.0
  flutter_spinkit: ^5.1.0
  toast: ^0.1.5
  cached_network_image: ^3.1.0
  auto_size_text: ^2.1.0
  get_storage: ^2.0.3
  hive: ^2.0.4
  shared_preferences: ^2.0.8


dev_dependencies: 
  flutter_test:
    sdk: flutter

flutter_launcher_name: 
  name: iStore

flutter_icons: 
  android: app_icon_round
  image_path: assets/images/app_icon_round.png
  ios: true

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

